# Generated by Django 5.2.7 on 2025-10-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('is_available', models.BooleanField(default=True)),
                ('adoption_status', models.CharField(max_length=100)),
            ],
        ),
    ]
