# Generated by Django 5.2.7 on 2025-10-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0002_adoptionrequest_petuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='description',
        ),
    ]
