# Generated by Django 5.2.7 on 2025-10-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0003_rename_name_pets_type_remove_pets_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='adoption_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
