# Generated by Django 5.2.7 on 2025-10-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0004_alter_pets_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='is_available',
            field=models.CharField(choices=[('availabile', 'Availabile'), ('notavailabile', 'Not Availabile')], default='availabile', max_length=20),
        ),
    ]
