# Generated by Django 5.2.7 on 2025-10-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0005_alter_pets_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='adoption_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='pets',
            name='is_available',
            field=models.CharField(choices=[('Availabile', 'Availabile'), ('Not Availabile', 'Not Availabile')], default='availabile', max_length=20),
        ),
    ]
