# Generated by Django 5.2.7 on 2025-10-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0006_alter_pets_adoption_status_alter_pets_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petuser',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
