# Generated by Django 5.2.7 on 2025-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0007_alter_petuser_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='commitment',
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adoption_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
