# Generated by Django 5.2.7 on 2025-10-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0008_remove_adoptionrequest_commitment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
