# Generated by Django 5.2.7 on 2025-10-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0009_adoptionrequest_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
