# Generated by Django 5.2.7 on 2025-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0010_pets_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
